{
 "title": "Nextcloud Audit Logs",
 "description": "Grafana dashboard for viewing Nextcloud audit logs with data collected by Loki/Promtail",
 "tags": [
  "nextcloud",
  "audit",
  "loki"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   {
    "name": "jobname",
    "query": {}
   },
   {
    "name": "filename",
    "label": "nextcloudaudit",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Logins", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "login attempts by unique remote IP",
   "type": "stat",
   "description": "this can also mean successful logins",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(remoteAddr) (count_over_time({job=\"$jobname\", filename=\"$filename\"} | json | url=~`/log.*`  message !~ `.*.(S|s)uccessful.*`  __error__=\"\"[$__range]))",
     "legendFormat": "{{ user }}"
    }
   ]
  },
  {
   "title": "login attempts by user",
   "type": "stat",
   "description": "Anonymous users are scripts or talk logins",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(user) (count_over_time({job=\"$jobname\", filename=\"$filename\"} | json message=\"message\", remoteAddr=\"remoteAddr\", time=\"time\", userAgent=\"userAgent\", user=\"user\", url=\"url\" | message!~\".*(S|s)uccessful.*\"| __error__=\"\" [$__interval]))",
     "legendFormat": "{{ user }}"
    }
   ]
  },
  {
   "title": "login attempts by unique remote IP",
   "type": "timeseries",
   "description": "This can also mean successful logins. If this value increases rapidly, it may be a DDOS attack.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by(remoteAddr) (count_over_time({job=\"$jobname\", filename=\"$filename\"} | json | url=~`/log.*`  message !~ `.*.(S|s)uccessful.*`  __error__=\"\"[$__range]))",
     "legendFormat": "{{ user }}"
    }
   ]
  },
  {
   "title": "login attempts with unknown user",
   "type": "stat",
   "description": "Attempted logins with invalid username. If a certain username appears more often than 1, it may be that the username was read out of eher via a databreach.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(wrongUser) (count_over_time({job=\"$jobname\", filename=\"$filename\"} | json | url=~`/log.*`  message !~ `.*.(S|s)uccessful.*` | pattern `<_>\\\"<wrongUser>\\\"` | __error__=\"\"[$__range]))",
     "legendFormat": "{{ wrongUser }}"
    }
   ]
  },
  {
   "title": "Logins",
   "type": "table",
   "description": "All logins",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "{job=\"$jobname\", filename=\"$filename\"} | json | url=~`/log.*` | pattern `<_>Login attempt: \\\"<userName>\\\"` | pattern `<_>Login successful: \\\"<userName>\\\"` | pattern `<_>Failed two factor attempt by user <userName> `| pattern `<_>Successful two factor attempt by user <userName> ` | __error__=\"\""
    }
   ]
  },
  {
   "title": "User file interactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "File changes by authenticated users",
     "type": "table",
     "description": "Changes made by registered users.",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 58 },
     "targets": [
      {
       "expr": "{job=\"$jobname\", filename=\"$filename\"}| json | url=~\"/remote.php/dav/.*\" method!~\"REPORT\" method!~\"PROPFIND\" method!~\"OPTIONS\"  | pattern `<_>File<_> \\\"/<_>/<fileName>\\\"` | __error__=\"\""
      }
     ]
    },
    {
     "title": "Files deleted from trash",
     "type": "stat",
     "description": "Files deleted from the trash bin. These are irretrievably deleted.",
     "gridPos": { "h": 5, "w": 2, "x": 0, "y": 71 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (message) (count_over_time({job=\"$jobname\", filename=\"$filename\"} | json message=\"message\", remoteAddr=\"remoteAddr\", time=\"time\", userAgent=\"userAgent\", user=\"user\", url=\"url\", method=\"method\" | url=~\"/remote.php/dav/trashbin/.*\" method=\"DELETE\" | __error__=\"\" [$__interval]))"
      }
     ]
    },
    {
     "title": "Files deleted",
     "type": "stat",
     "description": "If a lot of files were deleted at once, you should take a closer look.",
     "gridPos": { "h": 5, "w": 2, "x": 2, "y": 71 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (message) (count_over_time({job=\"$jobname\", filename=\"$filename\"} | json message=\"message\", remoteAddr=\"remoteAddr\", time=\"time\", userAgent=\"userAgent\", user=\"user\", url=\"url\", method=\"method\" | url=~\"/remote.php/dav/.*\" url!~\"/remote.php/dav/.*./trash\" method=\"DELETE\" | __error__=\"\" [$__interval]))"
      }
     ]
    },
    {
     "title": "Files updated",
     "type": "stat",
     "description": "If a lot of files were changed at once, you should take a closer look.",
     "gridPos": { "h": 5, "w": 2, "x": 4, "y": 71 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (reqId) (count_over_time({job=\"$jobname\", filename=\"$filename\"} | json | url=~\"/apps/text/session/sync\" method=\"POST\" | __error__=\"\" [$__interval]))"
      }
     ]
    },
    {
     "title": "Files created",
     "type": "stat",
     "description": "Number of files created. If this number increases very much, there may be a problem.",
     "gridPos": { "h": 5, "w": 2, "x": 6, "y": 71 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (message) (count_over_time({job=\"$jobname\", filename=\"$filename\"} | json | message=~`File created.*` | __error__=\"\" [$__interval]))"
      }
     ]
    },
    {
     "title": "File downloads",
     "type": "stat",
     "description": "Number of downloads. These do not have to be different files.",
     "gridPos": { "h": 5, "w": 2, "x": 8, "y": 71 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (message) (count_over_time({job=\"$jobname\", filename=\"$filename\"} | json | url=~\".*.download.*\"  | __error__=\"\" [$__interval]))"
      }
     ]
    },
    {
     "title": "Files created",
     "type": "timeseries",
     "description": "Number of files created. If this number increases very much, there may be a problem.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 76 },
     "targets": [
      {
       "expr": "count by (message) (count_over_time({job=\"$jobname\", filename=\"$filename\"} | json | message=~`File created.*`| __error__=\"\" [$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "User modifications",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Changes",
     "type": "table",
     "description": "User changes, e.g. creation, deletion, deactivation, password change, etc.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 59 },
     "targets": [
      {
       "expr": "{job=\"$jobname\", filename=\"$filename\"} | json  | url=~`/ocs/v2.php/cloud/users.*` | pattern `<_>User created: \\\"<userName>\\\"` | pattern `<_>User deleted: \\\"<userName>\\\"`| pattern `<_>Password of user \\\"<userName>\\\"` | pattern `<_>Email<_>user <userName>\"` | pattern `<_>User \\\"<userName>\\\" added` | pattern `<_>User \\\"<userName>\\\"` | pattern `<_>User enabled: \\\"<userName>\\\"` | pattern `<_>User disabled: \\\"<userName>\\\"`| __error__=\"\""
      }
     ]
    }
   ]
  },
  {
   "title": "Shared Links",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Anonymous accesses via share link",
     "type": "table",
     "description": "Accesses without user login.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 60 },
     "targets": [
      {
       "expr": "{job=\"$jobname\", filename=\"$filename\"} | json | user=`--` | message=~\"The shared.*\" | pattern `<_>The shared folder with the token \\\"<accesstoken>\\\" by \\\"<sharedby>\\\"` | pattern `<_>The shared file with the token \\\"<accesstoken>\\\" by \\\"<sharedby>\\\"`"
      }
     ]
    },
    {
     "title": "Anonymous accesses via share link (count)",
     "type": "stat",
     "gridPos": { "h": 11, "w": 4, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by(time)(count_over_time({job=\"$jobname\", filename=\"$filename\"} | json | user=`--` | message=~\"The shared.*\" | pattern `<_>The shared folder with the token \\\"<accesstoken>\\\" by \\\"<sharedby>\\\"` | pattern `<_>The shared file with the token \\\"<accesstoken>\\\" by \\\"<sharedby>\\\"` | __error__=\"\" [$__interval]))"
      }
     ]
    },
    {
     "title": "Anonymous accesses by unique remote IPs",
     "type": "stat",
     "gridPos": { "h": 11, "w": 4, "x": 4, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by(remoteAddr)(count_over_time({job=\"$jobname\", filename=\"$filename\"} | json | user=`--` | message=~\"The shared.*\" | pattern `<_>The shared folder with the token \\\"<accesstoken>\\\" by \\\"<sharedby>\\\"` | pattern `<_>The shared file with the token \\\"<accesstoken>\\\" by \\\"<sharedby>\\\"` | __error__=\"\" [$__interval]))"
      }
     ]
    },
    {
     "title": "Possible folder shares with full write permission",
     "type": "stat",
     "description": "See permission changes panel below to find out if the full write permission has been revised again.",
     "gridPos": { "h": 11, "w": 4, "x": 8, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(shareID)(count_over_time({job=\"$jobname\", filename=\"$filename\"} | json | url=~`/ocs/v2.php/apps/files_sharing/api/v1/shares/.*` message!~`The password.*` | pattern `<_>The permissions of the shared folder \\\"/<sharedFileOrFolder>\\\"<_>\\\"<shareID>\\\"<_>\\\"<changedPermissionID>\\\"` | changedPermissionID=`31` | __error__=\"\" [$__interval]))"
      }
     ]
    },
    {
     "title": "Anonymous file operations via sharelink",
     "type": "table",
     "description": "Anonymous file operations via share link. Accesses without user login.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 82 },
     "targets": [
      {
       "expr": "{job=\"$jobname\", filename=\"$filename\"}| json  | user=`--` | url!=`--` message!~`Login.*` | pattern `<_>File <_> \\\"/<_>/<fileName>\\\"` | pattern `<_>Preview <_> \\\"/<_>/<fileName>\\\"`| __error__=\"\""
      }
     ]
    },
    {
     "title": "Permission changes on shared folders or files",
     "type": "table",
     "description": "#### Files\n| Share permissions | Code |\n| ------------------| ---|\n| Read-only |17 |\n| Allow editing | 19 |\n#### Folders\n| Share permissions | Code |\n| ------------------| ---|\n| Write Protected |17 |\n|Allow upload and editing | 31 |\n|Allow upload and editing (no upload) | 27 |\n|Allow upload and editing (no upload, no editing) |25 |",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 93 },
     "targets": [
      {
       "expr": "{job=\"$jobname\", filename=\"$filename\"} | json | url=~`/ocs/v2.php/apps/files_sharing/api/v1/shares/.*` | message!~`The password.*`| pattern `<_>The permissions of the shared folder \\\"/<sharedFileOrFolder>\\\"<_>\\\"<shareID>\\\"<_>\\\"<changedPermissionID>\\\"` | pattern `<_>The permissions of the shared file \\\"/<sharedFileOrFolder>\\\"<_>\\\"<shareID>\\\"<_>\\\"<changedPermissionID>\\\"` | __error__=\"\""
      }
     ]
    }
   ]
  },
  {
   "title": "General log",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "logfile",
     "type": "logs",
     "description": "General nextcloud audit logs with references to events",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "{job=\"$jobname\", filename=\"$filename\"} | json | message=~\"Login successful.*\" | line_format \"🟩 🌐 IP {{.remoteAddr}} 👥 {{.user}} 🗩 {{.message }} 🖳 {{.userAgent}} {{.method}} {{.url }} {{.userAgent}}\""
      },
      {
       "expr": "{job=\"$jobname\", filename=\"$filename\"} | json | url=~`/log.*`  message !~ `.*.(S|s)uccessful.*` | pattern `<_>. \\\"<wrongUser>\\\"` | line_format \"🟥 🌐 IP {{.remoteAddr}} 👥 {{.wrongUser}} 🗩 {{.message }} 🖳 {{.userAgent}} {{.method}} {{.url }} {{.userAgent}}\""
      },
      {
       "expr": "{job=\"$jobname\", filename=\"$filename\"}| json | url=~\"/remote.php/dav/.*\" method!~\"REPORT\" method!~\"PROPFIND\" method!~\"OPTIONS\"  | pattern `<_>File<_> \\\"/<_>/<fileName>\\\"` | line_format \"🟩 🌐 IP {{.remoteAddr}} 👥 {{.user}} 🗩 {{.message }} 🖳 {{.userAgent}} {{.method}} {{.url }} {{.userAgent}}\""
      },
      {
       "expr": "{job=\"$jobname\", filename=\"$filename\"} | json  | url=~`/ocs/v2.php/cloud/users.*` | pattern `<_>User created: \\\"<userName>\\\"` | pattern `<_>User deleted: \\\"<userName>\\\"`| pattern `<_>Password of user \\\"<userName>\\\"` | pattern `<_>Email<_>user <userName>\"` | pattern `<_>User \\\"<userName>\\\" added` | pattern `<_>User \\\"<userName>\\\"` | pattern `<_>User enabled: \\\"<userName>\\\"` | pattern `<_>User disabled: \\\"<userName>\\\"`| line_format \"🟥 🌐 IP {{.remoteAddr}} 👥 {{.userName}} 🗩 {{.message }} 🖳 {{.userAgent}} {{.method}} {{.url }} {{.userAgent}}\""
      },
      {
       "expr": "{job=\"$jobname\", filename=\"$filename\"} | json | user=`--` | message=~\"The shared.*\" | pattern `<_>The shared folder with the token \\\"<accesstoken>\\\" by \\\"<sharedby>\\\"` | pattern `<_>The shared file with the token \\\"<accesstoken>\\\" by \\\"<sharedby>\\\"` | line_format \"🟨 🌐 IP {{.remoteAddr}} 👥 anonymous 🗩 {{.message }} 🖳 {{.userAgent}} {{.method}} {{.url }} {{.userAgent}}\""
      },
      {
       "expr": "{job=\"$jobname\", filename=\"$filename\"} | json | url=~`/ocs/v2.php/apps/files_sharing/api/v1/shares/.*` | message!~`The password.*`| pattern `<_>The permissions of the shared folder \\\"/<sharedFileOrFolder>\\\"<_>\\\"<shareID>\\\"<_>\\\"<changedPermissionID>\\\"` | pattern `<_>The permissions of the shared file \\\"/<sharedFileOrFolder>\\\"<_>\\\"<shareID>\\\"<_>\\\"<changedPermissionID>\\\"` | changedPermissionID=~`(19|25|31)`| line_format \"🟥 🌐 IP {{.remoteAddr}} 👥 {{.userName}} 🗩 {{.message }} 🖳 {{.userAgent}} {{.method}} {{.url }} {{.userAgent}}\""
      },
      {
       "expr": "{job=\"$jobname\", filename=\"$filename\"} | json | url=~`/ocs/v2.php/apps/files_sharing/api/v1/shares/.*` | message!~`The password.*`| pattern `<_>The permissions of the shared folder \\\"/<sharedFileOrFolder>\\\"<_>\\\"<shareID>\\\"<_>\\\"<changedPermissionID>\\\"` | pattern `<_>The permissions of the shared file \\\"/<sharedFileOrFolder>\\\"<_>\\\"<shareID>\\\"<_>\\\"<changedPermissionID>\\\"` | changedPermissionID!~`(19|25|31)`| line_format \"🟩 🌐 IP {{.remoteAddr}} 👥 {{.userName}} 🗩 {{.message }} 🖳 {{.userAgent}} {{.method}} {{.url }} {{.userAgent}}\""
      },
      {
       "expr": "{job=\"$jobname\", filename=\"$filename\"} | json | message=~\"Login successful.*\" | line_format \"🟩 🌐 IP {{.remoteAddr}} 👥 {{.user}} 🗩 {{.message }} 🖳 {{.userAgent}} {{.method}} {{.url }} {{.userAgent}}\""
      }
     ]
    }
   ]
  }
 ]
}